using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdvantEdgeAPI.Models
{
    public enum Status
    {
        STARTED,
        PROCESSED,
        COMPLETED,
        ERROR
    }

    public class Transaction
    {
        [Key]
        public Guid Id { get; set; }
        //the information passed by the client
        public string Body { get; set; }
        //the information generated by the 3rd party
        public string Detail { get; set; }
        //the current status of the request, maybe use an enum instead?
        public string Status { get; set; }
        
    }
}
